version: '3.8'
services:
  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: walletrest
      POSRTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: walletrest_app
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/walletrest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATADOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always

volumes:
  db-data: